// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: UIEMF

#ifndef UI_ANALYSIS_H
#define UI_ANALYSIS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Analysis
extern void ui_Analysis_screen_init(void);
extern void ui_Analysis_screen_destroy(void);
extern lv_obj_t * ui_Analysis;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_AnalysisRFstrengthArc;
extern lv_obj_t * ui_AnalysisEmotionArc;
extern lv_obj_t * ui_GSRtext4;
extern lv_obj_t * ui_Statetext6;
extern lv_obj_t * ui_GSRtext10;
extern lv_obj_t * ui_AnalysisRFstregnthtext;
extern lv_obj_t * ui_AnalysisEmotionalCalmnesstext;
extern lv_obj_t * ui_GSRtext12;
extern void ui_event_backbutton3(lv_event_t * e);
extern lv_obj_t * ui_backbutton3;
extern lv_obj_t * ui_backtextbutton3;
extern lv_obj_t * ui_Roller1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

