// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: UIEMF

#include "../ui.h"

lv_obj_t * ui_Analysis = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_AnalysisRFstrengthArc = NULL;
lv_obj_t * ui_AnalysisEmotionArc = NULL;
lv_obj_t * ui_GSRtext4 = NULL;
lv_obj_t * ui_Statetext6 = NULL;
lv_obj_t * ui_GSRtext10 = NULL;
lv_obj_t * ui_AnalysisRFstregnthtext = NULL;
lv_obj_t * ui_AnalysisEmotionalCalmnesstext = NULL;
lv_obj_t * ui_GSRtext12 = NULL;
lv_obj_t * ui_backbutton3 = NULL;
lv_obj_t * ui_backtextbutton3 = NULL;
lv_obj_t * ui_Roller1 = NULL;
// event funtions
void ui_event_backbutton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_detect, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_detect_screen_init);
    }
}

// build funtions

void ui_Analysis_screen_init(void)
{
    ui_Analysis = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Analysis, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Analysis);
    lv_img_set_src(ui_Image3, &ui_img_3_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 489
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AnalysisRFstrengthArc = lv_arc_create(ui_Analysis);
    lv_obj_set_width(ui_AnalysisRFstrengthArc, 150);
    lv_obj_set_height(ui_AnalysisRFstrengthArc, 150);
    lv_obj_set_x(ui_AnalysisRFstrengthArc, -96);
    lv_obj_set_y(ui_AnalysisRFstrengthArc, -22);
    lv_obj_set_align(ui_AnalysisRFstrengthArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_AnalysisRFstrengthArc, 50);
    lv_arc_set_bg_angles(ui_AnalysisRFstrengthArc, 90, 449);
    lv_obj_set_style_outline_color(ui_AnalysisRFstrengthArc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_AnalysisRFstrengthArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_AnalysisRFstrengthArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_AnalysisRFstrengthArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_AnalysisRFstrengthArc, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AnalysisRFstrengthArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AnalysisRFstrengthArc, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_AnalysisRFstrengthArc, lv_color_hex(0xFAAEC2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_AnalysisRFstrengthArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_AnalysisRFstrengthArc, lv_color_hex(0xA5FDFC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AnalysisRFstrengthArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_AnalysisRFstrengthArc, lv_color_hex(0xFF99B8), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_AnalysisRFstrengthArc, LV_GRAD_DIR_HOR, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AnalysisRFstrengthArc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AnalysisRFstrengthArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AnalysisRFstrengthArc, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_AnalysisEmotionArc = lv_arc_create(ui_Analysis);
    lv_obj_set_width(ui_AnalysisEmotionArc, 150);
    lv_obj_set_height(ui_AnalysisEmotionArc, 150);
    lv_obj_set_x(ui_AnalysisEmotionArc, 93);
    lv_obj_set_y(ui_AnalysisEmotionArc, -23);
    lv_obj_set_align(ui_AnalysisEmotionArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_AnalysisEmotionArc, 50);
    lv_arc_set_bg_angles(ui_AnalysisEmotionArc, 90, 449);

    lv_obj_set_style_arc_color(ui_AnalysisEmotionArc, lv_color_hex(0xD2F4F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_AnalysisEmotionArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_AnalysisEmotionArc, lv_color_hex(0xA5FDFC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AnalysisEmotionArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_AnalysisEmotionArc, lv_color_hex(0xFF99B8), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_AnalysisEmotionArc, LV_GRAD_DIR_HOR, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AnalysisEmotionArc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AnalysisEmotionArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AnalysisEmotionArc, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_GSRtext4 = lv_label_create(ui_Analysis);
    lv_obj_set_width(ui_GSRtext4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GSRtext4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GSRtext4, -98);
    lv_obj_set_y(ui_GSRtext4, 85);
    lv_obj_set_align(ui_GSRtext4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GSRtext4, "  RF\nStength");
    lv_obj_set_style_text_font(ui_GSRtext4, &ui_font_DotGothic24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Statetext6 = lv_label_create(ui_Analysis);
    lv_obj_set_width(ui_Statetext6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Statetext6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Statetext6, 95);
    lv_obj_set_y(ui_Statetext6, 85);
    lv_obj_set_align(ui_Statetext6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Statetext6, "Emotional\nCalmness");
    lv_obj_set_style_text_font(ui_Statetext6, &ui_font_DotGothic24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GSRtext10 = lv_label_create(ui_Analysis);
    lv_obj_set_width(ui_GSRtext10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GSRtext10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GSRtext10, -77);
    lv_obj_set_y(ui_GSRtext10, -21);
    lv_obj_set_align(ui_GSRtext10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GSRtext10, "%");
    lv_obj_set_style_text_font(ui_GSRtext10, &ui_font_DotGothic24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AnalysisRFstregnthtext = lv_label_create(ui_Analysis);
    lv_obj_set_width(ui_AnalysisRFstregnthtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalysisRFstregnthtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalysisRFstregnthtext, -106);
    lv_obj_set_y(ui_AnalysisRFstregnthtext, -21);
    lv_obj_set_align(ui_AnalysisRFstregnthtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AnalysisRFstregnthtext, "52");
    lv_obj_set_style_text_font(ui_AnalysisRFstregnthtext, &ui_font_DotGothic24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AnalysisEmotionalCalmnesstext = lv_label_create(ui_Analysis);
    lv_obj_set_width(ui_AnalysisEmotionalCalmnesstext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalysisEmotionalCalmnesstext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalysisEmotionalCalmnesstext, 83);
    lv_obj_set_y(ui_AnalysisEmotionalCalmnesstext, -23);
    lv_obj_set_align(ui_AnalysisEmotionalCalmnesstext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AnalysisEmotionalCalmnesstext, "52");
    lv_obj_set_style_text_font(ui_AnalysisEmotionalCalmnesstext, &ui_font_DotGothic24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GSRtext12 = lv_label_create(ui_Analysis);
    lv_obj_set_width(ui_GSRtext12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GSRtext12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GSRtext12, 112);
    lv_obj_set_y(ui_GSRtext12, -23);
    lv_obj_set_align(ui_GSRtext12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GSRtext12, "%");
    lv_obj_set_style_text_font(ui_GSRtext12, &ui_font_DotGothic24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backbutton3 = lv_btn_create(ui_Analysis);
    lv_obj_set_width(ui_backbutton3, 67);
    lv_obj_set_height(ui_backbutton3, 32);
    lv_obj_set_x(ui_backbutton3, 171);
    lv_obj_set_y(ui_backbutton3, -128);
    lv_obj_set_align(ui_backbutton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbutton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backbutton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backbutton3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backbutton3, 127, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_backbutton3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_backbutton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_backbutton3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_backbutton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backtextbutton3 = lv_label_create(ui_Analysis);
    lv_obj_set_width(ui_backtextbutton3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backtextbutton3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backtextbutton3, 170);
    lv_obj_set_y(ui_backtextbutton3, -128);
    lv_obj_set_align(ui_backtextbutton3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backtextbutton3, "Back");
    lv_obj_set_style_text_font(ui_backtextbutton3, &ui_font_DotGothic16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller1 = lv_roller_create(ui_Analysis);
    lv_roller_set_options(ui_Roller1, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller1, 100);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller1, 756);
    lv_obj_set_y(ui_Roller1, -402);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_backbutton3, ui_event_backbutton3, LV_EVENT_ALL, NULL);

}

void ui_Analysis_screen_destroy(void)
{
    if(ui_Analysis) lv_obj_del(ui_Analysis);

    // NULL screen variables
    ui_Analysis = NULL;
    ui_Image3 = NULL;
    ui_AnalysisRFstrengthArc = NULL;
    ui_AnalysisEmotionArc = NULL;
    ui_GSRtext4 = NULL;
    ui_Statetext6 = NULL;
    ui_GSRtext10 = NULL;
    ui_AnalysisRFstregnthtext = NULL;
    ui_AnalysisEmotionalCalmnesstext = NULL;
    ui_GSRtext12 = NULL;
    ui_backbutton3 = NULL;
    ui_backtextbutton3 = NULL;
    ui_Roller1 = NULL;

}
