// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: UIEMF

#include "../ui.h"

lv_obj_t * ui_detect = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_backbutton = NULL;
lv_obj_t * ui_detialbuttonlowmidrf = NULL;
lv_obj_t * ui_detialbuttonhighrf = NULL;
lv_obj_t * ui_backtextbutton = NULL;
lv_obj_t * ui_detialbuttoneeg = NULL;
lv_obj_t * ui_detialbuttongsr = NULL;
lv_obj_t * ui_EEGtext = NULL;
lv_obj_t * ui_GSRtext = NULL;
lv_obj_t * ui_lowrftext = NULL;
lv_obj_t * ui_highrftext = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Image11 = NULL;
// event funtions
void ui_event_backbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_homepage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_homepage_screen_init);
    }
}

void ui_event_detialbuttonlowmidrf(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Low_mid_RF1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Low_mid_RF1_screen_init);
    }
}

void ui_event_detialbuttonhighrf(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_High_RF, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_High_RF_screen_init);
    }
}

void ui_event_detialbuttoneeg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_EEG_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_EEG_Screen_screen_init);
    }
}

void ui_event_detialbuttongsr(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_GSR_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_GSR_Screen_screen_init);
    }
}

// build funtions

void ui_detect_screen_init(void)
{
    ui_detect = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_detect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_detect);
    lv_img_set_src(ui_Image7, &ui_img_2_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 489
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_detect);
    lv_img_set_src(ui_Image10, &ui_img_backgroundpage2_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backbutton = lv_btn_create(ui_detect);
    lv_obj_set_width(ui_backbutton, 67);
    lv_obj_set_height(ui_backbutton, 32);
    lv_obj_set_x(ui_backbutton, 171);
    lv_obj_set_y(ui_backbutton, -128);
    lv_obj_set_align(ui_backbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backbutton, 127, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_backbutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_backbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_backbutton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_backbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_detialbuttonlowmidrf = lv_btn_create(ui_detect);
    lv_obj_set_width(ui_detialbuttonlowmidrf, 208);
    lv_obj_set_height(ui_detialbuttonlowmidrf, 116);
    lv_obj_set_x(ui_detialbuttonlowmidrf, 103);
    lv_obj_set_y(ui_detialbuttonlowmidrf, -46);
    lv_obj_set_align(ui_detialbuttonlowmidrf, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_detialbuttonlowmidrf, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_detialbuttonlowmidrf, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_detialbuttonlowmidrf, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_detialbuttonlowmidrf, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_detialbuttonlowmidrf, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_detialbuttonlowmidrf, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_detialbuttonlowmidrf, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_detialbuttonlowmidrf, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_detialbuttonhighrf = lv_btn_create(ui_detect);
    lv_obj_set_width(ui_detialbuttonhighrf, 208);
    lv_obj_set_height(ui_detialbuttonhighrf, 116);
    lv_obj_set_x(ui_detialbuttonhighrf, 106);
    lv_obj_set_y(ui_detialbuttonhighrf, 79);
    lv_obj_set_align(ui_detialbuttonhighrf, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_detialbuttonhighrf, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_detialbuttonhighrf, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_detialbuttonhighrf, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_detialbuttonhighrf, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_detialbuttonhighrf, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_detialbuttonhighrf, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_detialbuttonhighrf, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_detialbuttonhighrf, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backtextbutton = lv_label_create(ui_detect);
    lv_obj_set_width(ui_backtextbutton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backtextbutton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backtextbutton, 170);
    lv_obj_set_y(ui_backtextbutton, -128);
    lv_obj_set_align(ui_backtextbutton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backtextbutton, "Back");
    lv_obj_set_style_text_font(ui_backtextbutton, &ui_font_DotGothic16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_detialbuttoneeg = lv_btn_create(ui_detect);
    lv_obj_set_width(ui_detialbuttoneeg, 208);
    lv_obj_set_height(ui_detialbuttoneeg, 116);
    lv_obj_set_x(ui_detialbuttoneeg, -113);
    lv_obj_set_y(ui_detialbuttoneeg, -45);
    lv_obj_set_align(ui_detialbuttoneeg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_detialbuttoneeg, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_detialbuttoneeg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_detialbuttoneeg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_detialbuttoneeg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_detialbuttoneeg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_detialbuttoneeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_detialbuttoneeg, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_detialbuttoneeg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_detialbuttongsr = lv_btn_create(ui_detect);
    lv_obj_set_width(ui_detialbuttongsr, 208);
    lv_obj_set_height(ui_detialbuttongsr, 116);
    lv_obj_set_x(ui_detialbuttongsr, -113);
    lv_obj_set_y(ui_detialbuttongsr, 78);
    lv_obj_set_align(ui_detialbuttongsr, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_detialbuttongsr, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_detialbuttongsr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_detialbuttongsr, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_detialbuttongsr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_detialbuttongsr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_detialbuttongsr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_detialbuttongsr, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_detialbuttongsr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EEGtext = lv_label_create(ui_detect);
    lv_obj_set_width(ui_EEGtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EEGtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EEGtext, -192);
    lv_obj_set_y(ui_EEGtext, -84);
    lv_obj_set_align(ui_EEGtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EEGtext, "EEG");
    lv_obj_set_style_text_font(ui_EEGtext, &ui_font_DotGothic24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GSRtext = lv_label_create(ui_detect);
    lv_obj_set_width(ui_GSRtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GSRtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GSRtext, -191);
    lv_obj_set_y(ui_GSRtext, 39);
    lv_obj_set_align(ui_GSRtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GSRtext, "GSR");
    lv_obj_set_style_text_font(ui_GSRtext, &ui_font_DotGothic24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lowrftext = lv_label_create(ui_detect);
    lv_obj_set_width(ui_lowrftext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lowrftext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lowrftext, 76);
    lv_obj_set_y(ui_lowrftext, -84);
    lv_obj_set_align(ui_lowrftext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lowrftext, "LOW-MID RF");
    lv_obj_set_style_text_font(ui_lowrftext, &ui_font_DotGothic24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_highrftext = lv_label_create(ui_detect);
    lv_obj_set_width(ui_highrftext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_highrftext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_highrftext, 59);
    lv_obj_set_y(ui_highrftext, 38);
    lv_obj_set_align(ui_highrftext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_highrftext, "HIGH RF");
    lv_obj_set_style_text_font(ui_highrftext, &ui_font_DotGothic24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_detect);
    lv_img_set_src(ui_Image5, &ui_img_16736989);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Image5, -113);
    lv_obj_set_y(ui_Image5, -44);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 20);

    ui_Image8 = lv_img_create(ui_detect);
    lv_img_set_src(ui_Image8, &ui_img_1412130330);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Image8, -114);
    lv_obj_set_y(ui_Image8, 78);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image8, 18);

    ui_Image9 = lv_img_create(ui_detect);
    lv_img_set_src(ui_Image9, &ui_img_1191746074);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1200
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1200
    lv_obj_set_x(ui_Image9, 103);
    lv_obj_set_y(ui_Image9, 75);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image9, 30);

    ui_Image11 = lv_img_create(ui_detect);
    lv_img_set_src(ui_Image11, &ui_img_2101998455);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 1200
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 1200
    lv_obj_set_x(ui_Image11, 100);
    lv_obj_set_y(ui_Image11, -53);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image11, 30);

    lv_obj_add_event_cb(ui_backbutton, ui_event_backbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_detialbuttonlowmidrf, ui_event_detialbuttonlowmidrf, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_detialbuttonhighrf, ui_event_detialbuttonhighrf, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_detialbuttoneeg, ui_event_detialbuttoneeg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_detialbuttongsr, ui_event_detialbuttongsr, LV_EVENT_ALL, NULL);

}

void ui_detect_screen_destroy(void)
{
    if(ui_detect) lv_obj_del(ui_detect);

    // NULL screen variables
    ui_detect = NULL;
    ui_Image7 = NULL;
    ui_Image10 = NULL;
    ui_backbutton = NULL;
    ui_detialbuttonlowmidrf = NULL;
    ui_detialbuttonhighrf = NULL;
    ui_backtextbutton = NULL;
    ui_detialbuttoneeg = NULL;
    ui_detialbuttongsr = NULL;
    ui_EEGtext = NULL;
    ui_GSRtext = NULL;
    ui_lowrftext = NULL;
    ui_highrftext = NULL;
    ui_Image5 = NULL;
    ui_Image8 = NULL;
    ui_Image9 = NULL;
    ui_Image11 = NULL;

}
