// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: UIEMF

#ifndef UI_DETECT_H
#define UI_DETECT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_detect
extern void ui_detect_screen_init(void);
extern void ui_detect_screen_destroy(void);
extern lv_obj_t * ui_detect;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image10;
extern void ui_event_backbutton(lv_event_t * e);
extern lv_obj_t * ui_backbutton;
extern void ui_event_detialbuttonlowmidrf(lv_event_t * e);
extern lv_obj_t * ui_detialbuttonlowmidrf;
extern void ui_event_detialbuttonhighrf(lv_event_t * e);
extern lv_obj_t * ui_detialbuttonhighrf;
extern lv_obj_t * ui_backtextbutton;
extern void ui_event_detialbuttoneeg(lv_event_t * e);
extern lv_obj_t * ui_detialbuttoneeg;
extern void ui_event_detialbuttongsr(lv_event_t * e);
extern lv_obj_t * ui_detialbuttongsr;
extern lv_obj_t * ui_EEGtext;
extern lv_obj_t * ui_GSRtext;
extern lv_obj_t * ui_lowrftext;
extern lv_obj_t * ui_highrftext;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image11;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

