// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: UIEMF

#ifndef UI_EEG_SCREEN_H
#define UI_EEG_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_EEG_Screen
extern void ui_EEG_Screen_screen_init(void);
extern void ui_EEG_Screen_screen_destroy(void);
extern lv_obj_t * ui_EEG_Screen;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_PanellowGSR1;
extern lv_obj_t * ui_PanellowGSR2;
extern lv_obj_t * ui_PanellowGSR3;
extern lv_obj_t * ui_PanellowGSR4;
extern lv_obj_t * ui_PanellowGSR5;
extern lv_obj_t * ui_EEGtext1;
extern lv_obj_t * ui_EEGtext2;
extern lv_obj_t * ui_EEGtext3;
extern void ui_event_backbutton1(lv_event_t * e);
extern lv_obj_t * ui_backbutton1;
extern lv_obj_t * ui_backtextbutton1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

