// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: UIEMF

#include "../ui.h"
#include "../ui_data.h"

lv_obj_t * ui_EEG_Screen = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_PanellowGSR1 = NULL;
lv_obj_t * ui_PanellowGSR2 = NULL;
lv_obj_t * ui_PanellowGSR3 = NULL;
lv_obj_t * ui_PanellowGSR4 = NULL;
lv_obj_t * ui_PanellowGSR5 = NULL;
lv_obj_t * ui_EEGtext1 = NULL;
lv_obj_t * ui_EEGtext2 = NULL;
lv_obj_t * ui_EEGtext3 = NULL;
lv_obj_t * ui_backbutton1 = NULL;
lv_obj_t * ui_backtextbutton1 = NULL;
// event funtions
void ui_event_backbutton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_detect, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_detect_screen_init);
    }
}

// build funtions

void ui_EEG_Screen_screen_init(void)
{
    ui_EEG_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_EEG_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_EEG_Screen);
    lv_img_set_src(ui_Image1, &ui_img_3_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 489
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanellowGSR1 = lv_obj_create(ui_EEG_Screen);
    lv_obj_set_width(ui_PanellowGSR1, 423);
    lv_obj_set_height(ui_PanellowGSR1, 45);
    lv_obj_set_x(ui_PanellowGSR1, -3);
    lv_obj_set_y(ui_PanellowGSR1, -74);
    lv_obj_set_align(ui_PanellowGSR1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanellowGSR1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanellowGSR1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanellowGSR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanellowGSR1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanellowGSR2 = lv_obj_create(ui_EEG_Screen);
    lv_obj_set_width(ui_PanellowGSR2, 423);
    lv_obj_set_height(ui_PanellowGSR2, 45);
    lv_obj_set_x(ui_PanellowGSR2, -1);
    lv_obj_set_y(ui_PanellowGSR2, -24);
    lv_obj_set_align(ui_PanellowGSR2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanellowGSR2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanellowGSR2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanellowGSR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanellowGSR2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanellowGSR3 = lv_obj_create(ui_EEG_Screen);
    lv_obj_set_width(ui_PanellowGSR3, 423);
    lv_obj_set_height(ui_PanellowGSR3, 45);
    lv_obj_set_x(ui_PanellowGSR3, -1);
    lv_obj_set_y(ui_PanellowGSR3, 26);
    lv_obj_set_align(ui_PanellowGSR3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanellowGSR3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanellowGSR3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanellowGSR3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanellowGSR3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanellowGSR4 = lv_obj_create(ui_EEG_Screen);
    lv_obj_set_width(ui_PanellowGSR4, 423);
    lv_obj_set_height(ui_PanellowGSR4, 45);
    lv_obj_set_x(ui_PanellowGSR4, -1);
    lv_obj_set_y(ui_PanellowGSR4, 76);
    lv_obj_set_align(ui_PanellowGSR4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanellowGSR4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanellowGSR4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanellowGSR4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanellowGSR4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanellowGSR5 = lv_obj_create(ui_EEG_Screen);
    lv_obj_set_width(ui_PanellowGSR5, 423);
    lv_obj_set_height(ui_PanellowGSR5, 45);
    lv_obj_set_x(ui_PanellowGSR5, -1);
    lv_obj_set_y(ui_PanellowGSR5, 128);
    lv_obj_set_align(ui_PanellowGSR5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanellowGSR5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanellowGSR5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanellowGSR5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanellowGSR5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EEGtext1 = lv_label_create(ui_EEG_Screen);
    lv_obj_set_width(ui_EEGtext1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EEGtext1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EEGtext1, -187);
    lv_obj_set_y(ui_EEGtext1, -112);
    lv_obj_set_align(ui_EEGtext1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EEGtext1, "EEG");
    lv_obj_set_style_text_font(ui_EEGtext1, &ui_font_DotGothic32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EEGtext2 = lv_label_create(ui_EEG_Screen);
    lv_obj_set_width(ui_EEGtext2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EEGtext2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EEGtext2, -141);
    lv_obj_set_y(ui_EEGtext2, 36);
    lv_obj_set_align(ui_EEGtext2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EEGtext2,
                      "Delta 0.5-4 Hz\n\n\nTheta 4-8 Hz\n\n\nAlpha 8-13 Hz\n\n\nBeta 13-30 Hz\n\n\nGamma 30-100 Hz\n");
    lv_obj_set_style_text_font(ui_EEGtext2, &ui_font_DotGothic16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EEGtext3 = lv_label_create(ui_EEG_Screen);
    lv_obj_set_width(ui_EEGtext3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EEGtext3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EEGtext3, 81);
    lv_obj_set_y(ui_EEGtext3, 25);
    lv_obj_set_align(ui_EEGtext3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EEGtext3,
                      "Deep sleep, very low \nalertness\n\nDrowsiness, light \nsleep, imagination\n\nRelaxed, \ncalm\n\nFocus, active thinking, \nalertness, tension\n\nHigher-level processing, \nIntense neural activity");
    lv_obj_set_style_text_font(ui_EEGtext3, &ui_font_DotGothic16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backbutton1 = lv_btn_create(ui_EEG_Screen);
    lv_obj_set_width(ui_backbutton1, 67);
    lv_obj_set_height(ui_backbutton1, 32);
    lv_obj_set_x(ui_backbutton1, 171);
    lv_obj_set_y(ui_backbutton1, -128);
    lv_obj_set_align(ui_backbutton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbutton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backbutton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backbutton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backbutton1, 127, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_backbutton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_backbutton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_backbutton1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_backbutton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backtextbutton1 = lv_label_create(ui_EEG_Screen);
    lv_obj_set_width(ui_backtextbutton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backtextbutton1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backtextbutton1, 170);
    lv_obj_set_y(ui_backtextbutton1, -128);
    lv_obj_set_align(ui_backtextbutton1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backtextbutton1, "Back");
    lv_obj_set_style_text_font(ui_backtextbutton1, &ui_font_DotGothic16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backbutton1, ui_event_backbutton1, LV_EVENT_ALL, NULL);

    ui_data_refresh_eeg();
}

void ui_EEG_Screen_screen_destroy(void)
{
    if(ui_EEG_Screen) lv_obj_del(ui_EEG_Screen);

    // NULL screen variables
    ui_EEG_Screen = NULL;
    ui_Image1 = NULL;
    ui_PanellowGSR1 = NULL;
    ui_PanellowGSR2 = NULL;
    ui_PanellowGSR3 = NULL;
    ui_PanellowGSR4 = NULL;
    ui_PanellowGSR5 = NULL;
    ui_EEGtext1 = NULL;
    ui_EEGtext2 = NULL;
    ui_EEGtext3 = NULL;
    ui_backbutton1 = NULL;
    ui_backtextbutton1 = NULL;

}
