// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: UIEMF

#include "../ui.h"
#include "../ui_data.h"

lv_obj_t * ui_GSR_Screen = NULL;
lv_obj_t * ui_GSR = NULL;
lv_obj_t * ui_PanellowGSR = NULL;
lv_obj_t * ui_PanelMildGSR = NULL;
lv_obj_t * ui_PanelModeratteGSR = NULL;
lv_obj_t * ui_PanelStrongGSR = NULL;
lv_obj_t * ui_GSRtext1 = NULL;
lv_obj_t * ui_GSRtext3 = NULL;
lv_obj_t * ui_GSRtext2 = NULL;
lv_obj_t * ui_backbutton2 = NULL;
lv_obj_t * ui_backtextbutton2 = NULL;
// event funtions
void ui_event_backbutton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_detect, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_detect_screen_init);
    }
}

// build funtions

void ui_GSR_Screen_screen_init(void)
{
    ui_GSR_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GSR_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GSR = lv_img_create(ui_GSR_Screen);
    lv_img_set_src(ui_GSR, &ui_img_3_png);
    lv_obj_set_width(ui_GSR, LV_SIZE_CONTENT);   /// 489
    lv_obj_set_height(ui_GSR, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_GSR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GSR, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_GSR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanellowGSR = lv_obj_create(ui_GSR_Screen);
    lv_obj_set_width(ui_PanellowGSR, 423);
    lv_obj_set_height(ui_PanellowGSR, 45);
    lv_obj_set_x(ui_PanellowGSR, -3);
    lv_obj_set_y(ui_PanellowGSR, -53);
    lv_obj_set_align(ui_PanellowGSR, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanellowGSR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanellowGSR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanellowGSR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanellowGSR, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelMildGSR = lv_obj_create(ui_GSR_Screen);
    lv_obj_set_width(ui_PanelMildGSR, 423);
    lv_obj_set_height(ui_PanelMildGSR, 45);
    lv_obj_set_x(ui_PanelMildGSR, -3);
    lv_obj_set_y(ui_PanelMildGSR, -3);
    lv_obj_set_align(ui_PanelMildGSR, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelMildGSR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanelMildGSR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelMildGSR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelMildGSR, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelModeratteGSR = lv_obj_create(ui_GSR_Screen);
    lv_obj_set_width(ui_PanelModeratteGSR, 423);
    lv_obj_set_height(ui_PanelModeratteGSR, 45);
    lv_obj_set_x(ui_PanelModeratteGSR, -3);
    lv_obj_set_y(ui_PanelModeratteGSR, 48);
    lv_obj_set_align(ui_PanelModeratteGSR, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelModeratteGSR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanelModeratteGSR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelModeratteGSR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelModeratteGSR, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelStrongGSR = lv_obj_create(ui_GSR_Screen);
    lv_obj_set_width(ui_PanelStrongGSR, 423);
    lv_obj_set_height(ui_PanelStrongGSR, 45);
    lv_obj_set_x(ui_PanelStrongGSR, -3);
    lv_obj_set_y(ui_PanelStrongGSR, 100);
    lv_obj_set_align(ui_PanelStrongGSR, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelStrongGSR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanelStrongGSR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelStrongGSR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelStrongGSR, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GSRtext1 = lv_label_create(ui_GSR_Screen);
    lv_obj_set_width(ui_GSRtext1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GSRtext1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GSRtext1, -114);
    lv_obj_set_y(ui_GSRtext1, 30);
    lv_obj_set_align(ui_GSRtext1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GSRtext1,
                      "1: |Change| < 20\n\n\n2: 20 <= |Change| < 80\n\n\n3: 80 <= |Change| < 200\n\n\n4: |Change|> = 200\n");
    lv_obj_set_style_text_font(ui_GSRtext1, &ui_font_DotGothic16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GSRtext3 = lv_label_create(ui_GSR_Screen);
    lv_obj_set_width(ui_GSRtext3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GSRtext3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GSRtext3, -45);
    lv_obj_set_y(ui_GSRtext3, 98);
    lv_obj_set_align(ui_GSRtext3, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_GSRtext3, "Stable / low arousal\n\n\nMild arousal\n\n\nModerate arousal\n\n\nStrong arousal");
    lv_obj_set_style_text_align(ui_GSRtext3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GSRtext3, &ui_font_DotGothic16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GSRtext2 = lv_label_create(ui_GSR_Screen);
    lv_obj_set_width(ui_GSRtext2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GSRtext2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GSRtext2, -187);
    lv_obj_set_y(ui_GSRtext2, -112);
    lv_obj_set_align(ui_GSRtext2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GSRtext2, "GSR");
    lv_obj_set_style_text_font(ui_GSRtext2, &ui_font_DotGothic32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backbutton2 = lv_btn_create(ui_GSR_Screen);
    lv_obj_set_width(ui_backbutton2, 67);
    lv_obj_set_height(ui_backbutton2, 32);
    lv_obj_set_x(ui_backbutton2, 171);
    lv_obj_set_y(ui_backbutton2, -128);
    lv_obj_set_align(ui_backbutton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbutton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backbutton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backbutton2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backbutton2, 127, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_backbutton2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_backbutton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_backbutton2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_backbutton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backtextbutton2 = lv_label_create(ui_GSR_Screen);
    lv_obj_set_width(ui_backtextbutton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backtextbutton2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backtextbutton2, 170);
    lv_obj_set_y(ui_backtextbutton2, -128);
    lv_obj_set_align(ui_backtextbutton2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backtextbutton2, "Back");
    lv_obj_set_style_text_font(ui_backtextbutton2, &ui_font_DotGothic16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backbutton2, ui_event_backbutton2, LV_EVENT_ALL, NULL);

    ui_data_refresh_gsr();
}

void ui_GSR_Screen_screen_destroy(void)
{
    if(ui_GSR_Screen) lv_obj_del(ui_GSR_Screen);

    // NULL screen variables
    ui_GSR_Screen = NULL;
    ui_GSR = NULL;
    ui_PanellowGSR = NULL;
    ui_PanelMildGSR = NULL;
    ui_PanelModeratteGSR = NULL;
    ui_PanelStrongGSR = NULL;
    ui_GSRtext1 = NULL;
    ui_GSRtext3 = NULL;
    ui_GSRtext2 = NULL;
    ui_backbutton2 = NULL;
    ui_backtextbutton2 = NULL;

}
