// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: UIEMF

#ifndef UI_GSR_SCREEN_H
#define UI_GSR_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_GSR_Screen
extern void ui_GSR_Screen_screen_init(void);
extern void ui_GSR_Screen_screen_destroy(void);
extern lv_obj_t * ui_GSR_Screen;
extern lv_obj_t * ui_GSR;
extern lv_obj_t * ui_PanellowGSR;
extern lv_obj_t * ui_PanelMildGSR;
extern lv_obj_t * ui_PanelModeratteGSR;
extern lv_obj_t * ui_PanelStrongGSR;
extern lv_obj_t * ui_GSRtext1;
extern lv_obj_t * ui_GSRtext3;
extern lv_obj_t * ui_GSRtext2;
extern void ui_event_backbutton2(lv_event_t * e);
extern lv_obj_t * ui_backbutton2;
extern lv_obj_t * ui_backtextbutton2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

