// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: UIEMF

#include "../ui.h"

lv_obj_t * ui_High_RF = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_GSRtext7 = NULL;
lv_obj_t * ui_GSRtext13 = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_Bar2 = NULL;
lv_obj_t * ui_Bar3 = NULL;
lv_obj_t * ui_Bar4 = NULL;
lv_obj_t * ui_backbutton5 = NULL;
lv_obj_t * ui_backtextbutton5 = NULL;
// event funtions
void ui_event_backbutton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_detect, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_detect_screen_init);
    }
}

// build funtions

void ui_High_RF_screen_init(void)
{
    ui_High_RF = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_High_RF, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_High_RF);
    lv_img_set_src(ui_Image4, &ui_img_3_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 489
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GSRtext7 = lv_label_create(ui_High_RF);
    lv_obj_set_width(ui_GSRtext7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GSRtext7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GSRtext7, -139);
    lv_obj_set_y(ui_GSRtext7, 18);
    lv_obj_set_align(ui_GSRtext7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GSRtext7, "5G Cellular\n\n5G NR\n\nWiFi 5 GHz\n\n");
    lv_obj_set_style_text_font(ui_GSRtext7, &ui_font_DotGothic24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GSRtext13 = lv_label_create(ui_High_RF);
    lv_obj_set_width(ui_GSRtext13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GSRtext13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GSRtext13, -149);
    lv_obj_set_y(ui_GSRtext13, -112);
    lv_obj_set_align(ui_GSRtext13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GSRtext13, "HIGH RF");
    lv_obj_set_style_text_font(ui_GSRtext13, &ui_font_DotGothic32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_High_RF);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 238);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, 69);
    lv_obj_set_y(ui_Bar1, -55);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xFAAEC2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar1, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar1, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Bar2 = lv_bar_create(ui_High_RF);
    lv_bar_set_value(ui_Bar2, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, 238);
    lv_obj_set_height(ui_Bar2, 10);
    lv_obj_set_x(ui_Bar2, 69);
    lv_obj_set_y(ui_Bar2, -5);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xFAAEC2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar2, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar2, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Bar3 = lv_bar_create(ui_High_RF);
    lv_bar_set_value(ui_Bar3, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar3, 238);
    lv_obj_set_height(ui_Bar3, 10);
    lv_obj_set_x(ui_Bar3, 70);
    lv_obj_set_y(ui_Bar3, 44);
    lv_obj_set_align(ui_Bar3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0xFAAEC2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar3, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar3, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Bar4 = lv_bar_create(ui_High_RF);
    lv_bar_set_value(ui_Bar4, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar4, 238);
    lv_obj_set_height(ui_Bar4, 10);
    lv_obj_set_x(ui_Bar4, 70);
    lv_obj_set_y(ui_Bar4, 91);
    lv_obj_set_align(ui_Bar4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0xFAAEC2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar4, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar4, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_backbutton5 = lv_btn_create(ui_High_RF);
    lv_obj_set_width(ui_backbutton5, 67);
    lv_obj_set_height(ui_backbutton5, 32);
    lv_obj_set_x(ui_backbutton5, 171);
    lv_obj_set_y(ui_backbutton5, -128);
    lv_obj_set_align(ui_backbutton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbutton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backbutton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backbutton5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backbutton5, 127, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_backbutton5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_backbutton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_backbutton5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_backbutton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backtextbutton5 = lv_label_create(ui_High_RF);
    lv_obj_set_width(ui_backtextbutton5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backtextbutton5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backtextbutton5, 170);
    lv_obj_set_y(ui_backtextbutton5, -128);
    lv_obj_set_align(ui_backtextbutton5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backtextbutton5, "Back");
    lv_obj_set_style_text_font(ui_backtextbutton5, &ui_font_DotGothic16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backbutton5, ui_event_backbutton5, LV_EVENT_ALL, NULL);

}

void ui_High_RF_screen_destroy(void)
{
    if(ui_High_RF) lv_obj_del(ui_High_RF);

    // NULL screen variables
    ui_High_RF = NULL;
    ui_Image4 = NULL;
    ui_GSRtext7 = NULL;
    ui_GSRtext13 = NULL;
    ui_Bar1 = NULL;
    ui_Bar2 = NULL;
    ui_Bar3 = NULL;
    ui_Bar4 = NULL;
    ui_backbutton5 = NULL;
    ui_backtextbutton5 = NULL;

}
