// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: UIEMF

#include "../ui.h"

lv_obj_t * uic_Detect;
lv_obj_t * ui_homepage = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Detectbutton = NULL;
lv_obj_t * ui_analysisbutton = NULL;
lv_obj_t * ui_detectbutttontext = NULL;
lv_obj_t * ui_analysisbuttontext = NULL;
lv_obj_t * ui_title = NULL;
// event funtions
void ui_event_Detectbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_detect, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_detect_screen_init);
    }
}

void ui_event_analysisbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Analysis, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Analysis_screen_init);
    }
}

// build funtions

void ui_homepage_screen_init(void)
{
    ui_homepage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_homepage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_homepage);
    lv_img_set_src(ui_Image6, &ui_img_1_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 489
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Detectbutton = lv_btn_create(ui_homepage);
    lv_obj_set_width(ui_Detectbutton, 151);
    lv_obj_set_height(ui_Detectbutton, 50);
    lv_obj_set_x(ui_Detectbutton, -116);
    lv_obj_set_y(ui_Detectbutton, 81);
    lv_obj_set_align(ui_Detectbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Detectbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Detectbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Detectbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Detectbutton, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Detectbutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Detectbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Detectbutton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Detectbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Detectbutton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Detectbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Detectbutton, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Detectbutton, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Detectbutton, &ui_font_DotGothic16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_analysisbutton = lv_btn_create(ui_homepage);
    lv_obj_set_width(ui_analysisbutton, 147);
    lv_obj_set_height(ui_analysisbutton, 50);
    lv_obj_set_x(ui_analysisbutton, 100);
    lv_obj_set_y(ui_analysisbutton, 82);
    lv_obj_set_align(ui_analysisbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_analysisbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_analysisbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_analysisbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_analysisbutton, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_analysisbutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_analysisbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_analysisbutton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_analysisbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_detectbutttontext = lv_label_create(ui_homepage);
    lv_obj_set_width(ui_detectbutttontext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_detectbutttontext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_detectbutttontext, -116);
    lv_obj_set_y(ui_detectbutttontext, 82);
    lv_obj_set_align(ui_detectbutttontext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_detectbutttontext, "Detect");
    lv_obj_set_style_text_font(ui_detectbutttontext, &ui_font_DotGothic16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_analysisbuttontext = lv_label_create(ui_homepage);
    lv_obj_set_width(ui_analysisbuttontext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_analysisbuttontext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_analysisbuttontext, 99);
    lv_obj_set_y(ui_analysisbuttontext, 81);
    lv_obj_set_align(ui_analysisbuttontext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_analysisbuttontext, "Analyze");
    lv_obj_set_style_text_font(ui_analysisbuttontext, &ui_font_DotGothic16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_title = lv_label_create(ui_homepage);
    lv_obj_set_width(ui_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_title, 2);
    lv_obj_set_y(ui_title, -29);
    lv_obj_set_align(ui_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_title, "VISUALISE \nINIVISIBILITY");
    lv_obj_set_style_text_font(ui_title, &ui_font_DotGothic32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Detectbutton, ui_event_Detectbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_analysisbutton, ui_event_analysisbutton, LV_EVENT_ALL, NULL);
    uic_Detect = ui_Detectbutton;

}

void ui_homepage_screen_destroy(void)
{
    if(ui_homepage) lv_obj_del(ui_homepage);

    // NULL screen variables
    ui_homepage = NULL;
    ui_Image6 = NULL;
    uic_Detect = NULL;
    ui_Detectbutton = NULL;
    ui_analysisbutton = NULL;
    ui_detectbutttontext = NULL;
    ui_analysisbuttontext = NULL;
    ui_title = NULL;

}
