// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: UIEMF

#ifndef UI_HOMEPAGE_H
#define UI_HOMEPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_homepage
extern void ui_homepage_screen_init(void);
extern void ui_homepage_screen_destroy(void);
extern lv_obj_t * ui_homepage;
extern lv_obj_t * ui_Image6;
extern void ui_event_Detectbutton(lv_event_t * e);
extern lv_obj_t * ui_Detectbutton;
extern void ui_event_analysisbutton(lv_event_t * e);
extern lv_obj_t * ui_analysisbutton;
extern lv_obj_t * ui_detectbutttontext;
extern lv_obj_t * ui_analysisbuttontext;
extern lv_obj_t * ui_title;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Detect;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

