// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: UIEMF

#ifndef UI_HIGH_RF_H
#define UI_HIGH_RF_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_High_RF
extern void ui_High_RF_screen_init(void);
extern void ui_High_RF_screen_destroy(void);
extern lv_obj_t * ui_High_RF;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_GSRtext7;
extern lv_obj_t * ui_GSRtext13;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_Bar4;
extern void ui_event_backbutton5(lv_event_t * e);
extern lv_obj_t * ui_backbutton5;
extern lv_obj_t * ui_backtextbutton5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

