// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: UIEMF

#include "../ui.h"

lv_obj_t * ui_Low_mid_RF1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_GSRtext9 = NULL;
lv_obj_t * ui_LOW_MID_RF = NULL;
lv_obj_t * ui_Bar6 = NULL;
lv_obj_t * ui_Bar7 = NULL;
lv_obj_t * ui_Bar5 = NULL;
lv_obj_t * ui_Bar8 = NULL;
lv_obj_t * ui_Bar9 = NULL;
lv_obj_t * ui_Bar10 = NULL;
lv_obj_t * ui_Bar11 = NULL;
lv_obj_t * ui_backbutton4 = NULL;
lv_obj_t * ui_backtextbutton4 = NULL;
lv_obj_t * ui_Image_lowrf_icon = NULL;
// event funtions

void ui_event_backbutton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_detect, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_detect_screen_init);
    }
}

// build funtions

void ui_Low_mid_RF1_screen_init(void)
{
    ui_Low_mid_RF1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Low_mid_RF1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Low_mid_RF1);
    lv_img_set_src(ui_Image2, &ui_img_3_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);

    ui_Image_lowrf_icon = lv_img_create(ui_Low_mid_RF1);
    lv_img_set_src(ui_Image_lowrf_icon, &ui_img_2101998455);
    lv_obj_set_width(ui_Image_lowrf_icon, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Image_lowrf_icon, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Image_lowrf_icon, -200);
    lv_obj_set_y(ui_Image_lowrf_icon, -112);
    lv_obj_set_align(ui_Image_lowrf_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_lowrf_icon, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(ui_Image_lowrf_icon, LV_OBJ_FLAG_SCROLLABLE);

    ui_backbutton4 = lv_btn_create(ui_Low_mid_RF1);
    lv_obj_set_width(ui_backbutton4, 67);
    lv_obj_set_height(ui_backbutton4, 32);
    lv_obj_set_x(ui_backbutton4, 171);
    lv_obj_set_y(ui_backbutton4, -128);
    lv_obj_set_align(ui_backbutton4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbutton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_backbutton4, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_backbutton4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backbutton4, 127, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_backbutton4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_backbutton4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_backbutton4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_backbutton4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backtextbutton4 = lv_label_create(ui_Low_mid_RF1);
    lv_obj_set_width(ui_backtextbutton4, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_backtextbutton4, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_backtextbutton4, 170);
    lv_obj_set_y(ui_backtextbutton4, -128);
    lv_obj_set_align(ui_backtextbutton4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backtextbutton4, "Back");
    lv_obj_set_style_text_font(ui_backtextbutton4, &ui_font_DotGothic16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GSRtext9 = lv_label_create(ui_Low_mid_RF1);
    lv_obj_set_width(ui_GSRtext9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GSRtext9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GSRtext9, -151);
    lv_obj_set_y(ui_GSRtext9, 25);
    lv_obj_set_align(ui_GSRtext9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GSRtext9,
                      "fm radio\n\nweather radio\n\naviation vhf\n\nism\n\nuhf television\n\ncellular gsm\n\naircraft ads-b");
    lv_obj_set_style_text_font(ui_GSRtext9, &ui_font_DotGothic16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LOW_MID_RF = lv_label_create(ui_Low_mid_RF1);
    lv_obj_set_width(ui_LOW_MID_RF, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LOW_MID_RF, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LOW_MID_RF, -129);
    lv_obj_set_y(ui_LOW_MID_RF, -112);
    lv_obj_set_align(ui_LOW_MID_RF, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LOW_MID_RF, "LOW MID RF");
    lv_obj_set_style_text_font(ui_LOW_MID_RF, &ui_font_DotGothic32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar6 = lv_bar_create(ui_Low_mid_RF1);
    lv_bar_set_value(ui_Bar6, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar6, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar6, 238);
    lv_obj_set_height(ui_Bar6, 10);
    lv_obj_set_x(ui_Bar6, 69);
    lv_obj_set_y(ui_Bar6, -78);
    lv_obj_set_align(ui_Bar6, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar6, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar6, lv_color_hex(0xFAAEC2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar6, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar6, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Bar7 = lv_bar_create(ui_Low_mid_RF1);
    lv_bar_set_value(ui_Bar7, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar7, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar7, 238);
    lv_obj_set_height(ui_Bar7, 10);
    lv_obj_set_x(ui_Bar7, 69);
    lv_obj_set_y(ui_Bar7, -42);
    lv_obj_set_align(ui_Bar7, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar7, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar7, lv_color_hex(0xFAAEC2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar7, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar7, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar7, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar7, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Bar5 = lv_bar_create(ui_Low_mid_RF1);
    lv_bar_set_value(ui_Bar5, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar5, 238);
    lv_obj_set_height(ui_Bar5, 10);
    lv_obj_set_x(ui_Bar5, 69);
    lv_obj_set_y(ui_Bar5, -8);
    lv_obj_set_align(ui_Bar5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar5, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar5, lv_color_hex(0xFAAEC2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar5, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar5, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Bar8 = lv_bar_create(ui_Low_mid_RF1);
    lv_bar_set_value(ui_Bar8, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar8, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar8, 238);
    lv_obj_set_height(ui_Bar8, 10);
    lv_obj_set_x(ui_Bar8, 69);
    lv_obj_set_y(ui_Bar8, 27);
    lv_obj_set_align(ui_Bar8, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar8, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar8, lv_color_hex(0xFAAEC2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar8, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar8, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar8, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar8, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Bar9 = lv_bar_create(ui_Low_mid_RF1);
    lv_bar_set_value(ui_Bar9, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar9, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar9, 238);
    lv_obj_set_height(ui_Bar9, 10);
    lv_obj_set_x(ui_Bar9, 69);
    lv_obj_set_y(ui_Bar9, 61);
    lv_obj_set_align(ui_Bar9, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar9, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar9, lv_color_hex(0xFAAEC2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar9, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar9, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar9, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar9, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Bar10 = lv_bar_create(ui_Low_mid_RF1);
    lv_bar_set_value(ui_Bar10, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar10, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar10, 238);
    lv_obj_set_height(ui_Bar10, 10);
    lv_obj_set_x(ui_Bar10, 69);
    lv_obj_set_y(ui_Bar10, 95);
    lv_obj_set_align(ui_Bar10, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar10, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar10, lv_color_hex(0xFAAEC2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar10, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar10, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar10, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar10, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Bar11 = lv_bar_create(ui_Low_mid_RF1);
    lv_bar_set_value(ui_Bar11, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar11, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar11, 238);
    lv_obj_set_height(ui_Bar11, 10);
    lv_obj_set_x(ui_Bar11, 69);
    lv_obj_set_y(ui_Bar11, 128);
    lv_obj_set_align(ui_Bar11, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar11, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar11, lv_color_hex(0xFAAEC2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar11, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar11, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar11, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar11, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backbutton4, ui_event_backbutton4, LV_EVENT_ALL, NULL);

}

void ui_Low_mid_RF1_screen_destroy(void)
{
    if(ui_Low_mid_RF1) lv_obj_del(ui_Low_mid_RF1);

    // NULL screen variables
    ui_Low_mid_RF1 = NULL;
    ui_Image2 = NULL;
    ui_GSRtext9 = NULL;
    ui_LOW_MID_RF = NULL;
    ui_Bar6 = NULL;
    ui_Bar7 = NULL;
    ui_Bar5 = NULL;
    ui_Bar8 = NULL;
    ui_Bar9 = NULL;
    ui_Bar10 = NULL;
    ui_Bar11 = NULL;
    ui_backbutton4 = NULL;
    ui_backtextbutton4 = NULL;
    ui_Image_lowrf_icon = NULL;

}
