// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: UIEMF

#ifndef UI_LOW_MID_RF1_H
#define UI_LOW_MID_RF1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Low_mid_RF1
extern void ui_Low_mid_RF1_screen_init(void);
extern void ui_Low_mid_RF1_screen_destroy(void);
extern lv_obj_t * ui_Low_mid_RF1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_GSRtext9;
extern lv_obj_t * ui_LOW_MID_RF;
extern lv_obj_t * ui_Bar6;
extern lv_obj_t * ui_Bar7;
extern lv_obj_t * ui_Bar5;
extern lv_obj_t * ui_Bar8;
extern lv_obj_t * ui_Bar9;
extern lv_obj_t * ui_Bar10;
extern lv_obj_t * ui_Bar11;
extern void ui_event_backbutton4(lv_event_t * e);
extern lv_obj_t * ui_backbutton4;
extern lv_obj_t * ui_backtextbutton4;
extern lv_obj_t * ui_Image_lowrf_icon;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

