"""Fix SquareLine 1.6 alpha image exports for LV_COLOR_DEPTH 16.

SquareLine exports TRUE_COLOR_ALPHA as 4-byte BGRA pixels. LVGL 16-bit expects
3 bytes (TRUE_COLOR_ALPHA) or 2 bytes (TRUE_COLOR). This script converts
4-byte exports to TRUE_COLOR RGB565 (2 bytes/pixel).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

SKETCH_ROOT = Path(__file__).resolve().parents[1]
IMAGES_DIR = SKETCH_ROOT / "images"

# Compiled into flash (see ui_sources.c). Skip huge icon assets (use stubs).
COMPILED_IMAGES = (
    "ui_img_backgroundpage2_png.c",
    "ui_img_3_png.c",
)


def parse_image_c(path: Path) -> tuple[int, int, str, list[int]]:
    text = path.read_text(encoding="utf-8")
    w_match = re.search(r"\.header\.w\s*=\s*(\d+)", text)
    h_match = re.search(r"\.header\.h\s*=\s*(\d+)", text)
    cf_match = re.search(r"\.header\.cf\s*=\s*(LV_IMG_CF_\w+)", text)
    if not (w_match and h_match and cf_match):
        raise ValueError(f"{path.name}: missing image header fields")

    raw = [int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})", text)]
    return int(w_match.group(1)), int(h_match.group(1)), cf_match.group(1), raw


def bgra_to_rgb565_bytes(b: int, g: int, r: int) -> tuple[int, int]:
    rgb565 = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    return rgb565 & 0xFF, (rgb565 >> 8) & 0xFF


def needs_conversion(raw: list[int], w: int, h: int, cf: str) -> bool:
    if cf == "LV_IMG_CF_TRUE_COLOR":
        return False
    if len(raw) == w * h * 4:
        return True
    if len(raw) == w * h * 2 and cf == "LV_IMG_CF_TRUE_COLOR":
        return False
    if len(raw) == w * h * 3 and cf == "LV_IMG_CF_TRUE_COLOR_ALPHA":
        return False
    raise ValueError(f"unexpected data size {len(raw)} for {w}x{h} cf={cf}")


def convert_pixels(raw: list[int]) -> list[int]:
    out: list[int] = []
    for i in range(0, len(raw), 4):
        b, g, r, _a = raw[i : i + 4]
        lo, hi = bgra_to_rgb565_bytes(b, g, r)
        out.append(lo)
        out.append(hi)
    return out


def format_c_array(pixels: list[int]) -> str:
    lines: list[str] = []
    for i in range(0, len(pixels), 16):
        chunk = pixels[i : i + 16]
        line = "    " + ",".join(f"0x{b:02X}" for b in chunk) + ","
        lines.append(line)
    if lines:
        lines[-1] = lines[-1].rstrip(",")
    return "\n".join(lines)


def write_converted(path: Path, var_base: str, asset_note: str, w: int, h: int, pixels: list[int]) -> None:
    data_name = f"{var_base}_data"
    body = format_c_array(pixels)
    content = f"""// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: UIEMF
// NOTE: Auto-fixed for LV_COLOR_DEPTH 16 (4-byte BGRA -> TRUE_COLOR RGB565).

#include "../ui.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
    #define LV_ATTRIBUTE_MEM_ALIGN
#endif

// IMAGE DATA: {asset_note}
const LV_ATTRIBUTE_MEM_ALIGN uint8_t {data_name}[] = {{
{body}
}};
const lv_img_dsc_t {var_base} = {{
    .header.always_zero = 0,
    .header.w = {w},
    .header.h = {h},
    .data_size = sizeof({data_name}),
    .header.cf = LV_IMG_CF_TRUE_COLOR,
    .data = {data_name}
}};
"""
    path.write_text(content, encoding="utf-8")


def convert_file(path: Path) -> str:
    w, h, cf, raw = parse_image_c(path)
    if not needs_conversion(raw, w, h, cf):
        return f"skip {path.name} (already OK)"

    var_base = path.stem
    asset_match = re.search(r"// IMAGE DATA: (.+)", path.read_text(encoding="utf-8"))
    asset_note = asset_match.group(1) if asset_match else path.name

    pixels = convert_pixels(raw)
    write_converted(path, var_base, asset_note, w, h, pixels)
    return f"fixed {path.name}: {len(raw)} -> {len(pixels)} bytes"


def main(argv: list[str]) -> int:
    targets: list[Path]
    if len(argv) > 1:
        targets = [Path(p) for p in argv[1:]]
    else:
        targets = [IMAGES_DIR / name for name in COMPILED_IMAGES]

    for path in targets:
        if not path.is_file():
            print(f"missing {path}")
            continue
        print(convert_file(path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
