// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: UIEMF

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

static void ui_apply_bringup_fixes(void)
{
    if(ui_homepage) {
        lv_obj_set_style_bg_color(ui_homepage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_homepage, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    if(ui_title) {
        lv_obj_set_style_text_color(ui_title, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    if(ui_detectbutttontext) {
        lv_obj_set_style_text_color(ui_detectbutttontext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    if(ui_analysisbuttontext) {
        lv_obj_set_style_text_color(ui_analysisbuttontext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    // Only homepage at boot; _ui_screen_change() lazy-inits the rest on first visit.
    ui_homepage_screen_init();
    ui_apply_bringup_fixes();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_homepage);
}

void ui_destroy(void)
{
    ui_homepage_screen_destroy();
    ui_detect_screen_destroy();
    ui_EEG_Screen_screen_destroy();
    ui_GSR_Screen_screen_destroy();
    ui_Analysis_screen_destroy();
    ui_High_RF_screen_destroy();
    ui_Low_mid_RF1_screen_destroy();
}
