// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: UIEMF

#ifndef _UIEMF_UI_H
#define _UIEMF_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <lvgl.h>

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_homepage.h"
#include "screens/ui_detect.h"
#include "screens/ui_EEG_Screen.h"
#include "screens/ui_GSR_Screen.h"
#include "screens/ui_Analysis.h"
#include "screens/ui_High_RF.h"
#include "screens/ui_Low_mid_RF1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1_png);    // assets/1.png
LV_IMG_DECLARE(ui_img_2_png);    // assets/2.png
LV_IMG_DECLARE(ui_img_backgroundpage2_png);    // assets/BACKGROUNDPAGE2.png
LV_IMG_DECLARE(ui_img_16736989);    // assets/noun-electroencephalogram-8371085.png
LV_IMG_DECLARE(ui_img_1412130330);    // assets/noun-skin-7996238.png
LV_IMG_DECLARE(ui_img_1191746074);    // assets/noun-signal-high-3555187.png
LV_IMG_DECLARE(ui_img_2101998455);    // assets/noun-signal-low-3555199.png
LV_IMG_DECLARE(ui_img_3_png);    // assets/3.png

// FONTS
LV_FONT_DECLARE(ui_font_DotGothic12);
LV_FONT_DECLARE(ui_font_DotGothic16);
LV_FONT_DECLARE(ui_font_DotGothic24);
LV_FONT_DECLARE(ui_font_DotGothic32);
LV_FONT_DECLARE(ui_font_DotGothic8);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
